name: EntityManager
main: milk.entitymanager.EntityManager
version: "1.3"
api: ["1.0.0"]

load: STARTUP
author: SW-Team
depend: ["PureEntities"]
description: control entity plugin
website: https://github.com/SW-Team/EntityManager

commands:
  entitymanager:
    description: control entity command
    aliases: ["entity", "ent", "em"]
    usage: "/entitymanager <remove/spawn/check>"
    permission: entitymanager.command
permissions:
  entitymanager.command:
    description: ""
    default: op